#!/bin/sh

cd "$(dirname "$0")"

if [ -z "$RECONOS" -o ! -d "$RECONOS" -o -z "$XILINX" -o ! -d "$XILINX" ] ; then
	echo "Please source the ReconOS config script before calling this script." >&2
	exit 1
fi

xtclsh sort_demo_test.tcl create_project
